#include <Zmey/World.h>
#include <Zmey/Components/ComponentManager.h>
#include <Zmey/Components/TransformManager.h>
#include <Zmey/Components/TagManager.h>

interface Zmey::EntityId {
}
interface Zmey::Name {
    constructor(string str);
}
interface Zmey::Components::TransformInstance {
    Zmey::Vector3 position();
}
interface Zmey::Components::TransformManager {
    Zmey::Components::TransformInstance lookup(Zmey::EntityId id);
}
interface Zmey::Components::TagManager {
    Zmey::EntityId findFirstByTag(Zmey::Name tag);
}
interface Zmey::Components::RectangleManager {
}
interface Zmey::World {
    anyof<Manager> getManager(int index);
    Zmey::EntityId getFirstEntity();
}
